### ISSUE TITLE
Could we possibly have a version where the names are same as reportrts for PC. Because we can't just use 1 db to have the tickets sync

### ISSUE THREAD

**Issue by LNET-Arns** [ProjectInfinity/ReportRTS-Pocket-Edition#3]

**Comment by ProjectInfinity** [comment]
Names? Also ReportRTS Pocket Edition does not support multiserver configurations.

**Comment by LNET-Arns** [comment]
Well what I mean is that we would like to have the the MCPE version on the same db as the PC version 
but we are unable to as thing like reportrtstickets are reportrtsrequests on the pc version

**Comment by ProjectInfinity** [comment]
You can change the ReportRTS PC tables by changing the storage prefix, that
way you can have both in the same database.

**Comment by LNET-Arns** [comment]
Yea but I would like them to sync with eachother so we can read MCPE tickets from PC and vise versa

**Comment by ProjectInfinity** [comment]
That is not possible. They are not interchangeable because they work
differently.

**Comment by LNET-Arns** [comment]
Ok thanks anyway (Is there anyway you could make it be interlinked?)

**Comment by ProjectInfinity** [comment]
Not really, unfortunately.

And I don't think there is enough demand to warrant creating a command to read pocket edition tickets.

Instead what you could do is make a simple plugin that connects to the DB and lists the tickets from ReportRTS Pocket Edition. You can do this in a web page as well.
