### ISSUE TITLE
Alpha9?

### ISSUE THREAD

**Issue by ghost** [ProjectInfinity/ReportRTS-Pocket-Edition#5]
Can you update this to alpha9 if its not too much trouble?

Would love to have an in-game ticket plugin!

**Comment by MCCStudios** [comment]
Opened a pull request to update to API3 and made a fork with the changes https://github.com/MCCStudios/ReportRTS-Pocket-Edition

**Comment by ProjectInfinity** [comment]
Merged, thanks.
